<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useUIStore } from '../stores/uiStore'
import { useSyncStore } from '../stores/sync'
import SplitPane from '../components/layout/SplitPane.vue'
import ContentPane from '../components/content/ContentPane.vue'
import CodingPane from '../components/editor/CodingPane.vue'
import MobileNavigator from '../components/mobile/MobileNavigator.vue'
import TeamChat from '../components/collab/TeamChat.vue'
import ThemeToggle from '../components/common/ThemeToggle.vue'
import SharedWhiteboard from '../components/collab/SharedWhiteboard.vue'

const route = useRoute()
const router = useRouter()
const uiStore = useUIStore()
const syncStore = useSyncStore()

// 🔧 학생 역할을 즉시 설정 (자식 컴포넌트 마운트 전에 실행됨)
syncStore.setTeacherRole(false)

// 채팅 상태
const isChatOpen = ref(false)
const chatRef = ref(null)

// 한국 이름 목록
const koreanNames = [
  '홍길동', '김철수', '이영희', '박민수', '최지은',
  '정수진', '강민호', '윤서연', '임재현', '한지우',
  '오성민', '신예은', '조현우', '배수지', '남궁민',
  '서준호', '권나영', '양지훈', '송하늘', '안유진'
]

// 랜덤 학생 ID 생성 함수
const generateStudentId = () => {
  const randomStr = Math.random().toString(36).substring(2, 8)
  return `student_${randomStr}`
}

// 랜덤 한국 이름 선택 함수
const getRandomKoreanName = () => {
  const randomIndex = Math.floor(Math.random() * koreanNames.length)
  return koreanNames[randomIndex]
}

// 컴포넌트 마운트 시 학생 ID 초기화
onMounted(() => {
  // studentId가 없으면 자동 생성하고 URL에 추가
  if (!route.query.studentId) {
    const autoGeneratedId = generateStudentId()
    const autoGeneratedName = getRandomKoreanName()

    console.log('[학생 화면] 자동 생성된 ID:', autoGeneratedId, '이름:', autoGeneratedName)

    // URL에 파라미터 추가 (페이지 새로고침 없이)
    router.replace({
      query: {
        ...route.query,
        studentId: autoGeneratedId,
        studentName: autoGeneratedName
      }
    })
  }
})

// 집중 모드 상태 (sync store에서 읽기)
const isFocusMode = computed(() => syncStore.focusMode)

// 판서 내역이 있는지 여부
const hasWhiteboardPaths = computed(() => syncStore.whiteboardPaths.length > 0)

// 판서를 표시할지 여부: 집중 모드 + (판서 모드 활성화 OR 판서 내역이 있음)
const shouldShowWhiteboard = computed(() =>
  isFocusMode.value && (syncStore.isWhiteboardActive || hasWhiteboardPaths.value)
)

// 판서 동기화 모드: 집중 모드 + 판서 모드 + 교사 콘텐츠 너비가 설정됨
// (레이아웃 전환은 판서가 활성화될 때만)
const isWhiteboardSyncMode = computed(() =>
  isFocusMode.value &&
  syncStore.isWhiteboardActive &&
  syncStore.syncedContentPaneWidth > 0
)

// 화면 너비가 교사 콘텐츠 너비보다 작은 경우 (좌우 스크롤 필요)
const screenWidth = ref(typeof window !== 'undefined' ? window.innerWidth : 1920)
const isContentOverflow = computed(() =>
  isWhiteboardSyncMode.value && screenWidth.value < syncStore.syncedContentPaneWidth
)

// 모바일에서 화면 너비가 교사 콘텐츠 너비보다 작은 경우
const isMobileContentOverflow = computed(() =>
  isWhiteboardSyncMode.value && screenWidth.value < syncStore.syncedContentPaneWidth
)

// 현재 차시 정보
const currentChapter = {
  number: 1,
  title: '자바 기초 문법'
}

// 콘텐츠 패널 너비 계산 (판서 좌표 역정규화용)
const mainAreaRef = ref(null)
const contentPaneWidth = ref(0)

const updateContentPaneWidth = () => {
  if (mainAreaRef.value) {
    contentPaneWidth.value = mainAreaRef.value.clientWidth * (syncStore.splitPercent / 100)
  }
}

const updateScreenWidth = () => {
  screenWidth.value = window.innerWidth
}

// 분할 비율 변경 감지
const unwatchSplit = ref(null)

onMounted(() => {
  updateContentPaneWidth()
  updateScreenWidth()
  window.addEventListener('resize', updateContentPaneWidth)
  window.addEventListener('resize', updateScreenWidth)

  // splitPercent 변경 감지 (교사가 분할 비율 변경 시)
  unwatchSplit.value = syncStore.$subscribe(() => {
    updateContentPaneWidth()
  })
})

onUnmounted(() => {
  window.removeEventListener('resize', updateContentPaneWidth)
  window.removeEventListener('resize', updateScreenWidth)
  if (unwatchSplit.value) {
    unwatchSplit.value()
  }
})
</script>

<template>
  <div class="learning-interface">
    <!-- Desktop View -->
    <div v-if="!uiStore.isMobile" class="desktop-layout">
      <header class="top-bar glass-panel">
        <div class="left-controls">
          <button class="back-btn" @click="$router.back()" title="뒤로가기">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M19 12H5M12 19l-7-7 7-7"/>
            </svg>
          </button>
          <h2 class="title">{{ currentChapter.title }}</h2>
          <div class="live-badge" v-if="isFocusMode">LIVE</div>
        </div>
        <div class="right-actions" style="display: flex; gap: 1rem; align-items: center;">
          <ThemeToggle />
          <div class="chat-container" style="position: relative;">
            <button class="chat-btn" @click="isChatOpen = !isChatOpen">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
              </svg>
              <span v-if="chatRef?.unreadCount > 0" class="chat-badge">{{ chatRef.unreadCount }}</span>
            </button>
            <TeamChat :isOpen="isChatOpen" ref="chatRef" />
          </div>
        </div>
      </header>

      <div class="main-area" ref="mainAreaRef">
        <!-- 일반 모드: SplitPane 사용 -->
        <SplitPane v-if="!isWhiteboardSyncMode" :initialSplit="40">
          <template #first>
            <ContentPane />
          </template>
          <template #second>
            <CodingPane />
          </template>
        </SplitPane>

        <!-- 판서 동기화 모드: 교사 콘텐츠 너비에 맞춤 -->
        <div v-else class="synced-layout">
          <div
            class="synced-content-pane"
            :class="{ 'overflow-mode': isContentOverflow }"
            :style="{ width: syncStore.syncedContentPaneWidth + 'px', minWidth: syncStore.syncedContentPaneWidth + 'px' }"
          >
            <ContentPane />
            <!-- 판서 동기화 모드에서의 화이트보드 오버레이 -->
            <div class="whiteboard-overlay" v-if="shouldShowWhiteboard">
              <SharedWhiteboard
                mode="student"
                :contentScrollPosition="syncStore.contentScrollPosition"
                :contentPaneWidth="syncStore.syncedContentPaneWidth"
                :syncedPaths="syncStore.whiteboardPaths"
                :syncedCurrentPath="syncStore.currentDrawingPath"
                :readonly="true"
              />
            </div>
          </div>
          <div class="synced-coding-pane">
            <CodingPane />
          </div>
        </div>

        <!-- 일반 모드에서의 화이트보드 오버레이 -->
        <div class="whiteboard-overlay content-area-only" v-if="!isWhiteboardSyncMode && shouldShowWhiteboard">
          <SharedWhiteboard
            mode="student"
            :contentScrollPosition="syncStore.contentScrollPosition"
            :contentPaneWidth="contentPaneWidth"
            :syncedPaths="syncStore.whiteboardPaths"
            :syncedCurrentPath="syncStore.currentDrawingPath"
            :readonly="true"
          />
        </div>
      </div>
    </div>

    <!-- Mobile View -->
    <div v-else class="mobile-layout">
      <header class="mobile-top-bar glass-panel">
        <div class="left-controls">
          <button class="back-btn" @click="$router.back()" title="뒤로가기">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M19 12H5M12 19l-7-7 7-7"/>
            </svg>
          </button>
          <h2 class="title">{{ currentChapter.title }}</h2>
          <div class="live-badge" v-if="isFocusMode">LIVE</div>
        </div>
        <div class="right-actions" style="display: flex; gap: 1rem; align-items: center;">
          <ThemeToggle />
          <div class="chat-container" style="position: relative;">
            <button class="chat-btn" @click="isChatOpen = !isChatOpen">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
              </svg>
              <span v-if="chatRef?.unreadCount > 0" class="chat-badge">{{ chatRef.unreadCount }}</span>
            </button>
            <TeamChat :isOpen="isChatOpen" ref="chatRef" />
          </div>
        </div>
      </header>

      <!-- 판서 동기화 모드에서 콘텐츠 탭: 교사 너비에 맞춤 -->
      <div
        v-if="isWhiteboardSyncMode"
        v-show="uiStore.mobileViewMode === 'content'"
        class="mobile-content-synced"
        :class="{ 'overflow-mode': isMobileContentOverflow }"
      >
        <div
          class="synced-content-wrapper"
          :style="{ width: syncStore.syncedContentPaneWidth + 'px', minWidth: syncStore.syncedContentPaneWidth + 'px' }"
        >
          <ContentPane />
          <!-- 판서 동기화 모드 모바일 화이트보드 오버레이 -->
          <div class="whiteboard-overlay" v-if="shouldShowWhiteboard">
            <SharedWhiteboard
              mode="student"
              :contentScrollPosition="syncStore.contentScrollPosition"
              :contentPaneWidth="syncStore.syncedContentPaneWidth"
              :syncedPaths="syncStore.whiteboardPaths"
              :syncedCurrentPath="syncStore.currentDrawingPath"
              :readonly="true"
            />
          </div>
        </div>
      </div>

      <!-- 판서 동기화 모드에서 코드 탭: 일반 표시 -->
      <div
        v-if="isWhiteboardSyncMode"
        v-show="uiStore.mobileViewMode === 'code'"
        class="mobile-code"
      >
        <CodingPane />
      </div>

      <!-- 일반 모드: 탭 전환 -->
      <template v-if="!isWhiteboardSyncMode">
        <div class="mobile-content" v-show="uiStore.mobileViewMode === 'content'">
          <ContentPane />
          <!-- 일반 모드 모바일 화이트보드 오버레이 -->
          <div class="whiteboard-overlay" v-if="shouldShowWhiteboard">
            <SharedWhiteboard
              mode="student"
              :contentScrollPosition="syncStore.contentScrollPosition"
              :contentPaneWidth="screenWidth"
              :syncedPaths="syncStore.whiteboardPaths"
              :syncedCurrentPath="syncStore.currentDrawingPath"
              :readonly="true"
            />
          </div>
        </div>
        <div class="mobile-code" v-show="uiStore.mobileViewMode === 'code'">
          <CodingPane />
        </div>
      </template>

      <MobileNavigator />
    </div>
  </div>
</template>

<style scoped>
.learning-interface {
  width: 100vw;
  height: 100vh;
  height: 100dvh; /* iOS Safari 대응 - dynamic viewport height */
  background: var(--bg-primary);
  color: var(--text-primary);
}

.desktop-layout {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.top-bar {
  height: 45px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 var(--spacing-lg);
  border-bottom: 1px solid var(--border-color);
  position: relative;
  z-index: 50;
}

.left-controls {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.back-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--text-secondary);
  transition: all 0.2s;
}

.back-btn:hover {
  background: var(--hover-bg);
  color: var(--text-primary);
}

.title {
  font-size: 1.1rem;
  font-weight: bold;
}

.live-badge {
  background: var(--error-color);
  color: white;
  padding: 0.3rem 0.6rem;
  border-radius: 4px;
  font-size: 1rem;
  font-weight: bold;
  animation: pulse 2s infinite;
}

.main-area {
  flex: 1;
  overflow: hidden;
  position: relative;
}

/* 판서 동기화 레이아웃 */
.synced-layout {
  display: flex;
  height: 100%;
  width: 100%;
}

.synced-content-pane {
  height: 100%;
  flex-shrink: 0;
  overflow: hidden;
  position: relative; /* 화이트보드 오버레이 기준점 */
}

/* 콘텐츠 영역 오버플로우 시 좌우 스크롤 */
.synced-content-pane.overflow-mode {
  overflow-x: auto;
  overflow-y: hidden;
}

.synced-coding-pane {
  flex: 1;
  height: 100%;
  min-width: 200px;
  overflow: hidden;
  border-left: 1px solid var(--border-color);
}

.whiteboard-overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 1000;
  pointer-events: none; /* 학생은 판서 불가, 클릭 투과 */
}

.mobile-layout {
  height: 100%;
  max-height: 100%;
  display: flex;
  flex-direction: column;
  position: relative;
  overflow: hidden;
}

.mobile-top-bar {
  height: 45px;
  min-height: 45px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 var(--spacing-lg);
  border-bottom: 1px solid var(--border-color);
  position: relative;
  z-index: 50;
}

.chat-container {
  position: relative;
}

.chat-btn {
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: var(--bg-secondary);
  border: 1px solid var(--border-color);
  color: var(--text-primary);
  font-size: 1.1rem;
  cursor: pointer;
  transition: all 0.2s;
  position: relative;
}

.chat-btn:hover {
  background: var(--bg-tertiary);
}

.chat-badge {
  position: absolute;
  top: -2px;
  right: -2px;
  background: var(--danger-color);
  color: white;
  font-size: 0.6rem;
  min-width: 16px;
  height: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  font-weight: 700;
  padding: 0 3px;
  box-shadow: 0 2px 4px var(--shadow-color);
  border: 2px solid var(--bg-primary);
}

.mobile-content, .mobile-code {
  flex: 1;
  min-height: 0; /* flex item이 제대로 줄어들도록 */
  overflow: hidden;
  position: relative; /* 화이트보드 오버레이 기준점 */
}

/* 모바일 판서 동기화 모드 */
.mobile-content-synced {
  flex: 1;
  min-height: 0;
  overflow: hidden;
  position: relative;
}

.mobile-content-synced.overflow-mode {
  overflow-x: auto;
  overflow-y: hidden;
}

.synced-content-wrapper {
  height: 100%;
  overflow: hidden;
  position: relative; /* 화이트보드 오버레이 기준점 */
}

.mini-instruction {
  position: absolute;
  top: 50px; /* Clear editor toolbar (40px) + spacing */
  left: 1rem;
  right: 1rem;
  padding: 0.5rem 0.75rem;
  border-radius: var(--radius-md);
  font-size: 0.85rem;
  pointer-events: none; /* Let clicks pass through */
  background: rgba(30, 41, 59, 0.9); /* More opaque to be readable */
  border: 1px solid var(--text-accent);
  z-index: 50;
}

@keyframes pulse {
  0% { opacity: 1; }
  50% { opacity: 0.5; }
  100% { opacity: 1; }
}

/* 모바일 대응 */
@media (max-width: 768px) {
  .chat-btn {
    width: 36px;
    height: 36px;
  }

  .chat-btn svg {
    width: 18px;
    height: 18px;
  }
}
</style>
